### ISSUE TITLE
Child theme compatibility 

### ISSUE THREAD

**Issue by maneshtimilsina** [WordPress/twentytwentyfour#101]
Everyone is using `get_stylesheet_directory_uri()` to load images from assets in patterns. We can use `get_theme_file_uri()` to load assets so that the theme and patterns will work with child themes too.

**Comment by sabernhardt** [comment]
Twenty Twenty uses `get_theme_file_uri()` for images in its starter content, but all the bundled themes that have images in their block patterns use `get_template_directory_uri()` for them. Both functions should fetch the parent theme's resources. However, if there is no expectation or desire to add resources with the same filenames in a child theme (or to use the `theme_file_uri` filter), `get_template_directory_uri()` would be the more efficient choice.

I also think the enqueued stylesheet could follow Twenty Twenty-Two's example with `get_template_directory_uri()` instead of `get_stylesheet_directory_uri()`.

**Comment by kafleg** [comment]
Yes, I was also wondering why everyone is using `get_stylesheet_directory_uri()`. And I did the same in some patterns as well. LOL

**Comment by MaggieCabrera** [comment]
> I also think the enqueued stylesheet could follow Twenty Twenty-Two's example with `get_template_directory_uri()` instead of `get_stylesheet_directory_uri()`.

Let's do this

**Comment by MaggieCabrera** [comment]
Closing this since I see no more instances of `get_stylesheet_directory_uri` on trunk. Thank you for being on top of this!

**Comment by webmandesign** [comment]
I'm quite late to the party here, but I'd like to ask for the reasoning why image files are not child theme friendly here in TT4 patterns.

From my perspective having more generic image names and using `get_theme_file_uri()` instead of `get_template_directory_uri()` would be a better approach. (But I may look at things still from a classic theme point of view, so I prefer being able to override things via child theme.)

**Comment by MaggieCabrera** [comment]
> I'm quite late to the party here, but I'd like to ask for the reasoning why image files are not child theme friendly here in TT4 patterns.
> 
> From my perspective having more generic image names and using `get_theme_file_uri()` instead of `get_template_directory_uri()` would be a better approach. (But I may look at things still from a classic theme point of view, so I prefer being able to override things via child theme.)

These images are meant to be replaced, not reused. Same as the content. Classic themes are one way and the code never changes, so having a child theme make those decisions for the user makes sense. Block themes shift that In any case, images in the templates loaded from the theme are not optimized and don't have a lot of the attributes that an uploaded image has (all the different thumbnail sizes, srcset, etc), so it's very much encouraged that the change is done in the editor instead of loaded by the theme for this main reason. I hope that clarifies enough!
