### ISSUE TITLE
Update patterns to use font size presets nearly exclusively

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#201]
The theme should almost never use arbitrary font sizes. By doing so, we're locking the theme into a less malleable design system, which makes customization less intuitive and style variations less expressive. 

Instead we should leverage font size presets _almost_ exclusively. Outliers would be the very large text like in the RSVP pattern. 

<img width="670" alt="CleanShot 2023-09-05 at 15 13 06" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/5d8e5008-f369-45f1-9039-e676a7ff2514">

**Comment by MaggieCabrera** [comment]
I think we need one extra font size to cover some of the cases. We can have up to 5 presets before we trigger the component to be a dropdown, shall we do that?

<img width="275" alt="Screenshot 2023-09-05 at 22 05 41" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/b413d555-ce61-4c1c-844f-39653cc9edc9">

**Comment by richtabor** [comment]
> I think we need one extra font size to cover some of the cases. We can have up to 5 presets before we trigger the component to be a dropdown, shall we do that?

We should keep it at max five. I can look at consolidating one of the closer values.

**Comment by MaggieCabrera** [comment]
Let's add the font sizes to the readme file when we decide if we want to add one more or not

**Comment by pbking** [comment]
I find it tricky for most of these changes since 'small' is the default size and there's nothing smaller.

I agree we should add a size, but I think it should be XS rather than XXL.

(edit) but I guess those size labels (S, M, L, XL, XXL) aren't configurable are they?

In which case, if we add something smaller than the default "small" even if we CALL it "extra small" it's still labeled "S" and small labeled "S", etc.

Which is confusing, which would mean refactoring ALL of the current size values.

Which I think is what would be most helpful.

**Comment by pbking** [comment]
I've made that change (shifted all of the font sizes up and made a new smaller small) so that those values can be replaced by a variable.

Thoughts?

https://github.com/WordPress/twentytwentyfour/pull/263

**Comment by beafialho** [comment]
Yeah, this one is tricky. In my opinion patterns benefit from using unique font sizes for certain elements instead of relying on the theme-defined presets. The same thing goes for line heights or letter spacing. We may want to have a slightly more opinionated line height occasionally than our paragraph default, which adds character to the pattern. I also don't think we have to include the RVSP and FAQs size.

How do you feel about these sizes for paragraphs?

<img width="770" alt="Captura de ecrã 2023-09-07, às 16 26 03" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/e28c355c-84a4-41cd-8d65-910b94dd6845">

**Comment by richtabor** [comment]
@beafialho I have a PR (https://github.com/WordPress/twentytwentyfour/pull/268) that falls pretty close to your proposal here. A couple notable points, but most so is using `medium` as the body/default size, and expressing the type-scale from there — instead of `regular`. 

Pretty much the same thing, just different conventions to fit in the existing model a bit better.

**Comment by richtabor** [comment]
> I've made that change (shifted all of the font sizes up and made a new smaller small) so that those values can be replaced by a variable.

@pbking Good stuff! I riffed off of your idea in an alternate PR (https://github.com/WordPress/twentytwentyfour/pull/268) with a few tweaks (and focusing only on the JSON side of things). Mind taking a look?

**Comment by beafialho** [comment]
> but most so is using medium as the body/default size, and expressing the type-scale from there — instead of regular.

That works 👍🏼

**Comment by carolinan** [comment]
Has this been fixed?
These have custom sizes in the markup:
FAQ
Sidebar
Pricing
RSVP

**Comment by MaggieCabrera** [comment]
Some of the custom sizes need to stay if the presets are not close enough, let's go one by one with those and consult when needed

**Comment by MaggieCabrera** [comment]
I'm closing this one since I think the custom font sizes are there because presets would alter the design too much. We can reopen in a case by case basis if we feel something still needs tweaking
