### ISSUE TITLE
Home pattern should not have a group wrapper

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#270]
The home pattern should not be contained, but instead full width like it is on the template. 

We should move the `main` group block outside of this pattern and within the template. This pattern should only have pattern blocks in it (like the business about pattern). 

Current: 

<img width="1561" alt="CleanShot 2023-09-07 at 11 38 16" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/3ac46a24-7f07-483a-84f1-2ae77151392d">

**Comment by MaggieCabrera** [comment]
Ugh, I thought I fixed this? let me check

**Comment by richtabor** [comment]
I think if it's just the patterns, it'll flow right everywhere. Just need to move the wrapping group block to the template (if it's really necessary even 🤔) 

```
<!-- wp:pattern {"slug":"twentytwentyfour/hero"} /-->
<!-- wp:pattern {"slug":"twentytwentyfour/feature-grid"} /-->
<!-- wp:pattern {"slug":"twentytwentyfour/features-with-images"} /-->
<!-- wp:pattern {"slug":"twentytwentyfour/testimonial"} /-->
<!-- wp:pattern {"slug":"twentytwentyfour/posts"} /-->
<!-- wp:pattern {"slug":"twentytwentyfour/cta"} /-->
```

**Comment by MaggieCabrera** [comment]
We do need the main tag for a11y, otherwise we could go without. The reason why I included it in the pattern is because if you use it to create a page, you will have to manually add the group block for the same a11y reasons

**Comment by MaggieCabrera** [comment]
I think this is not an issue with the pattern but with the page template. The page template right now is not allowing full/wide width alignments. I would leave the home pattern the way it is (even include the same wrapper on the other full page templates) and fix the page template, which was on my list to do tomorrow first thing

**Comment by richtabor** [comment]
> We do need the main tag for a11y, otherwise we could go without. The reason why I included it in the pattern is because if you use it to create a page, you will have to manually add the group block for the same a11y reasons

The main tag should be part of the template, not the pattern. These starter patterns are just groups of patterns that you can move around, delete, add more to, etc. We can't guarantee the `main` wrapping div won't be duplicated, removed, or content moved outside of it.

**Comment by richtabor** [comment]
> The page template right now is not allowing full/wide width alignments. I would leave the home pattern the way it is (even include the same wrapper on the other full page templates) and fix the page template, which was on my list to do tomorrow first thing

This happens anywhere you add the pattern (pages or posts). I don't think it's a pattern issue.

**Comment by MaggieCabrera** [comment]
you are right, I have a fix for this

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/twentytwentyfour/pull/273

**Comment by Ren2049** [comment]
I use group wrappers on all my templates so that I can override the block spacing for each of the templates. E.g. landing page templates are just a stack of full-width section patterns where I don't want the global block spacing to take effect between them. Removing the group wrapper removes control and makes it harder to customize imo. 

Is there another way to get the patterns to line up without global block spacing, without diabling the block spacing globally?

I think a wrapper is also useful to make use of the cascading styles, e.g. if you want a somewhat different style for a certain template (think of bookish post styles and more corporate page differences) that many designers would want to implement. Having just global styles and styles per patterns causes a lot more work than having another layer like a template wrapper in-between.
