### ISSUE TITLE
Creating starter page patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#272]
Now that we're starting to bake in starter patterns for the "Choose a pattern" modal when adding a new page, we should land on a few consistencies. We currently have three such patterns: `page-business-about`, `page-newsletter-subscribe` and `home`.

Questions: 

#### Should all starter page patterns be scoped to the page post type? 

I think so. I wouldn't think that a landing page, home page, or about page pattern is relevant when writing a post. 

#### Should we prefix pattern file/slugs with `page-`?

I think this would help organize efforts and ensure we know what classification of pattern we are working on. 

#### Should page patterns only consist of core/pattern blocks?

Yes, otherwise we end up with issues like https://github.com/WordPress/twentytwentyfour/issues/270. If we limit them to only consist of other patterns (as much as possible) then we add functionality without overhead. If you fix an individual pattern, its changes are reflected in the page pattern.

**Comment by MaggieCabrera** [comment]
Should we have a page template without the post title? Because the flow will use page.html and that includes the post title block. On the same vein, should we have a blank template for cases where we don't even want the header or footer?

**Comment by richtabor** [comment]
> Should we have a page template without the post title? Because the flow will use page.html and that includes the post title block.

Yea, probably so. 

> On the same vein, should we have a blank template for cases where we don't even want the header or footer?

We did in Twenty Twenty-Three. Maybe, though eventually it should probably not a fixed template.

**Comment by Ren2049** [comment]
> Yes, otherwise we end up with issues like https://github.com/WordPress/twentytwentyfour/issues/270.

I don't really understand the issue. Can't you apply full width on individual patterns with the content-width toggle enabled on the outer group wrapper? I think users would lose a lot of control for overriding global styles in a still semi-global way without the group wrapper.

**Comment by richtabor** [comment]
> I don't really understand the issue. 

As-is your full page design is inserted at a max width of the content width setting (~600px).

**Comment by Ren2049** [comment]
But the full-width setting on the pattern group blocks override the content width anyway? Or have thse things changed since 6.3?

I've designed sections patterns so that their background is always full width, and their content set to wide. When then insert a section pattern (group) it's first contained by the editor, but setting it to full-width fixes this.

Actually it would be better if they're set to full width by default when inserting them, without requiring the manual action.

**Comment by richtabor** [comment]
That's what we're aiming for yes :)

**Comment by Ren2049** [comment]
Not a good trade off imo if the group block gets removed because it would mean even more manual action for those who want to customize things. Can't the editor be programmed to insert the patterns in full width without the removal of the outer group?

Dedicated section blocks or a dedicated template block would come in really handy..

**Comment by richtabor** [comment]
I don't think we're talking about the same thing. In the current scenario, you add a page pattern and have to figure out how to set it to a proper width. In a correct scenario you don't have to figure that out; it's added to the page as expected.

**Comment by Ren2049** [comment]
Of course we're talking about the same thing. You want to make it easy for beginners by removing the group block wrapper so that they don't have to toggle the full-width setting of the patterns they insert.

But don't you think that it's a bad trade-off if you remove the control that a group block on the template enables? Shouldn't this problem be solved in a less hacky way by fixing the default behavior of inserted patterns?

I can guarantee you that people will be frustrated with block spacing if they can't control it on a template basis. Same for typography because changing it per pattern isn't really great for productivity.

**Comment by richtabor** [comment]
> Remove the control that a group block on the template enables? Shouldn't this problem be solved in a less hacky way by fixing the default behavior of inserted patterns?

We're not removing the group block wrapper from the template; just the pattern. 

If you want further control at the content level to adjust spacing between items, then that's when you wrap items in a group block and position away. Instead of starting rough, you start right — then you can add/apply/personalize away.

**Comment by Ren2049** [comment]
> We're not removing the group block wrapper from the template; just the pattern.

Group = pattern in my mind, sorry. I understood that you wanted to flatten the template by removing the outer wrapper group because its presence contains the wrapped patterns to the narrow width.

> If you want further control at the content level to adjust spacing between items, then that's when you wrap items in a group block and position away.

If you don't remove the outer group wrapper that wraps all groups/patterns/sections then I can keep adjusting the spacing on it? Same for the groups wrapping the patterns for more detailed control? If they don't get removed then there's full control :)

I'm still not sure if we're on the same page haha. Thanks for your pacience with me :)

**Comment by MaggieCabrera** [comment]
I think https://github.com/WordPress/twentytwentyfour/pull/273 solves the issue with the wrapper, and it's the right thing to do. Is there anything you think the user can't still do with that implementation? also I agree on the naming convention to add page- before the name, same as adding hidden- to the ones that hide patterns from the inserter

**Comment by Ren2049** [comment]
@MaggieCabrera you've removed the outer group block, without it users will have to stick to the global styles settings e.g. for block spacing for the home page. 

Let's say you want to stack a bunch of full width patterns for a landing page which I think is the most common thing people will do, and those patterns have different background colors, background images etc. 

Now you have to deal with the global block spacing which doesn't respect the pattern background, but surfaces the global background color of the site creating some nasty gaps between the patterns.

Users will ask how to get rid of them, and instead of grouping the root level groups/patterns and adjust the block spacing there many will just remove the global block spacing alltogether (which will complicate things once they move beyond their home page landing designs).

I've tapped into this trap myself a couple of months ago before I spend a lot of hours in the editor and got more familiar with groups. Removing the global block spacing was the most straight forward way to get a landing page design going back then.

**Comment by MaggieCabrera** [comment]
I think this one has been covered
