### ISSUE TITLE
The image block border is not displaying properly when we used filter duotone

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#640]
**Description**
Hello Team,

I have worked on the Gutenberg "Image" block and found that its border color is not displaying properly while we use a duotone filter.

**Step-by-step reproduction instructions**

- Go to page Type / to choose a block
- Select the "image" block and upload any image
- Click on the block setting and try to change the duotone filter option.
- Then, set the border and its color.

**Expected behavior**
![image_block_back_end](https://github.com/WordPress/twentytwentyfour/assets/53076293/8dfcba36-92da-4d00-ad37-cbf9680b8a4e)

**Screenshots**
![issue_image_block_back_end](https://github.com/WordPress/twentytwentyfour/assets/53076293/6c9cbac3-283f-432a-943f-041db98ce879)

**Environment info**

- Device: Macbook M1
- OS: 13.5.2 (22G91)
- Browser: Google Chrome
- Version: 117.0.5938.149 (Official Build) (arm64)
- WordPress version: 6.3.1, Gutenberg 16.7.1, Theme active: Twenty Twenty-Four,

**Comment by MaggieCabrera** [comment]
I'm closing this because this is not a theme specific issue, but the default behaviour of the editor. I also think that it makes sense that duotone is affecting the border as it's part of the image. If you want the border to maintain it's color, use a group to wrap around the image and add the border to the group block:

<img width="752" alt="Screenshot 2023-10-13 at 09 54 38" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/bd585ce5-90b7-4808-b608-da2abc32cb72">

In the screenshot you see two border, the outer one is not affected by duotone
