### ISSUE TITLE
Add skip link for accessibility 

### ISSUE THREAD

**Issue by 00travelgirl00** [WordPress/twentytwentyfour#73]
Add a "jump to content" link as the first link in header.

See also the handbook part about it: https://make.wordpress.org/themes/handbook/review/accessibility/required/#skip-links 

An "back to top" can be helpful as well, but its not necessary.

**Comment by 00travelgirl00** [comment]
I just noted: the skip link is present, but not at the front page

**Comment by nielslange** [comment]
Happy to work on this. Can someone assign it to me? 😀

**Comment by carolinan** [comment]
I believe this has already been fixed in https://github.com/WordPress/twentytwentyfour/pull/95/files#diff-8e1f6cf2c375e16c2ac47296784d76ad80a7d38076d5346387615d16b42ac526

In block themes, the skip link is added automatically when there is a main element. I see that the link that explains this in the theme developer handbook is broken. I will try to look into that today or later this week.

**Comment by carolinan** [comment]
The page has been restored here: https://developer.wordpress.org/themes/functionality/block-theme-accessibility/

**Comment by nielslange** [comment]
> I believe this has already been fixed in https://github.com/WordPress/twentytwentyfour/pull/95/files#diff-8e1f6cf2c375e16c2ac47296784d76ad80a7d38076d5346387615d16b42ac526

Thanks for clarifying this, @carolinan. Shouldn't this issue be closed then? 🤔

**Comment by MaggieCabrera** [comment]
I think this has been solved already. If any template appears to not have the `main` tag, let's open a specific issue for it. Thank you!
