### ISSUE TITLE
How to Automatically Set the First Image in an Article as Featured Image?

### ISSUE THREAD

**Issue by ihuub** [WordPress/twentytwentyfour#732]
I have a WordPress website, and the images for my articles are hosted on an external image hosting service. Currently, I manually set the featured image for each post, but I want to automate this process by using code to set the first image in each article as the featured image. Does anyone have suggestions or code examples on how to achieve this?

WordPress version: 6.4.1

Theme in use: twentytwentyfour

**Comment by carolinan** [comment]
Hi!

The functionality that you describe is not available for **any** block theme without custom code because they use blocks to present all the different elements. 
Neither the image block or the featured image block that are available in WordPress has this feature built in. This feature would first need to be built in the Gutenberg plugin, tested, moved to WordPress, and then made available to the theme.
- The first step would be to search the Gutenberg GitHub repository to see if this feature has been requested.

It is possible that there already is a third-party image block plugin in the plugin directory that does this, but I have not seen one.

I would recommend trying to post your question in a developer oriented forum like Stackoverflow: https://stackoverflow.com/.

I am closing this issue because it is not specific to this theme.
