### ISSUE TITLE
The Image block alignment is not proper

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#735]
**Description**
Hello Team,

I have worked on the "**image**" block and found that its alignment setting is not displaying properly.

**Step-by-step reproduction instructions**

1. Go to page Type / to choose a block
2. Select the Image block
3. Upload Image
4. Change its alignment to "Align Right" from "components-toolbar-group."
5. Update. Page
6. Check front view.

**Expected behavior**
**Front-end**
<img width="1439" alt="CleanShot 2023-12-01 at 14 52 18@2x" src="https://github.com/WordPress/twentytwentyfour/assets/53076293/e5b07aa9-ee0b-4597-be1e-29a6e7a542ed">

**Screenshots**
**Front-end**
<img width="1440" alt="CleanShot 2023-12-01 at 14 53 10@2x" src="https://github.com/WordPress/twentytwentyfour/assets/53076293/e480b751-901a-4b28-ac6a-6bf80f2ba733">

**Environment info**
Device: Macbook M1
OS: 13.6.1 (22G313)
Browser: Google Chrome
Version 119.0.6045.159 (Official Build) (arm64)
WordPress version: 6.4.1 running, Gutenberg 17.1.3, Theme active: Twenty Twenty-Four,

Thanks,

**Comment by carolinan** [comment]
Hi
This is not an issue with the theme, but a known issue with the image block. 
The image block does not have CSS for clearing floated elements. It is also difficult to add this type of clear to the block itself because it would change how the image block works on existing sites, breaking site layouts.


To solve this **in any block theme**, add the image to a container like a group block.
