### ISSUE TITLE
Quote block typography  font size is not working as expected

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#745]
**Description**
Hello,

I have reviewed the "**Quote**" block and found that its typography font size settings are not working properly for admin.
I have set typography as "Huge" but it's not reflected in the admin.

**Step-by-step reproduction instructions**

Go to admin and select the first "Quote" block.
Add its paragraph text & citation. text
Go to block settings and change its typography font size.
Update the page and check its admin text and front-end text.

**Expected behavior**
![quotes](https://github.com/WordPress/twentytwentyfour/assets/53076293/209cf5d2-9353-4ee2-b7f9-89ae405fb229)

**Screenshots**
![quotes_issue](https://github.com/WordPress/twentytwentyfour/assets/53076293/3430d415-3711-4ebd-980a-8554caead1f8)

**Environment info**
Device: Macbook M1
OS: 14.2.1 (23C71)
Browser: Google Chrome
Version 120.0.6099.216 (Official Build) (arm64)
WordPress version: 6.4.2 running, Gutenberg 17.4.1, Theme active: Twenty Twenty-Four,

Thanks,

**Additional context**
-

**Comment by carolinan** [comment]
Hi
The screenshot does not show the default design for the quote block in this theme.

Kindly add the step by step instructions of how to reproduce what is shown in the screenshot, and clearly describe what is not working as expected.

Is the problem that the cite is not changing size? This is the intended design for the theme, and not a bug.

**Comment by carolinan** [comment]
This is the default design:
<img width="1512" alt="quote block" src="https://github.com/WordPress/twentytwentyfour/assets/7422055/906704fc-0943-446b-ac9f-f657be4a1f36">

**Comment by carolinan** [comment]
The theme does not have a font size called Huge, but perhaps that was just a typo :)

**Comment by viralsampat-multidots** [comment]
Hello @carolinan 

This is just a typo, I meant that if we changed the typography size to "**XXL**" it is not reflected in the admin.  But it's reflected on the front-end as expected.

Thanks,

**Comment by carolinan** [comment]
Can you please specify more details?:

>The screenshot does not show the default design for the quote block in this theme.

>Kindly add the step by step instructions of how to reproduce what is shown in the screenshot, and clearly describe what is >not working as expected.

>Is the problem that the cite is not changing size? This is the intended design for the theme, and not a bug.

**Comment by carolinan** [comment]
In Twenty Twenty-Three, the cite does not increase in size.
In Twenty Twenty-Two, the cite does increase in size.
In Twenty Twenty-One, we know that the sizes are broken because of the theme CSS (reported on trac)
In Twenty Twenty, the cite does not increase in size
In Twenty Nineteen, we know that the sizes are broken because of the theme CSS (reported on trac)

Non default themes:
YITH Wonder, the cite does increase in size.
Astra,  the cite does increase in size, but it is broken on the front
Hello, the cite does increase in size.
Ocean WP, the cite does increase in size.
GeneratePress, the cite does increase in size.

So it is no surprise that users do expect the cite to change when the quote block font size option is used.

@onemaggie @richtabor @beafialho Do we need to reconsider and see this as a bug, not a theme design choice?

**Comment by carolinan** [comment]
PingIng the correct user name ;) @MaggieCabrera

**Comment by MaggieCabrera** [comment]
I see the `cite` element was styled, instead of the block. It could have been done either way, but I thought styling the block should override the element styles. Perhaps this is a specificity issue in the block? In that case it would require a Gutenberg issue instead.

**Comment by MaggieCabrera** [comment]
We are archiving this repo, but I don't think the theme is doing anything wrong here, so the solution should be found upstream
